/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Route segments */
        get: operations["getSegments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A single coordinate pair — longitude then latitude, in that order, in decimal degrees (RFC 7946 §3.1.1). Elevation is deliberately excluded: core.route_segment.geom is geometry(LineString, 4326), two-dimensional, so a third element would mean the pipeline has introduced a Z value nothing downstream expects. */
        Position: number[];
        /** @description A GeoJSON LineString. Coordinates are always WGS 84 (EPSG:4326). The database also holds core.route_segment.geom_proj in EPSG:26917 for distance work; that projected form must never be serialised through this schema — enforced by the ST_SRID contract test (plan §5 Stage D, task D2a). */
        LineStringGeometry: {
            /** @enum {string} */
            type: "LineString";
            coordinates: components["schemas"]["Position"][];
        };
        /** @description Non-geometric attributes of a route segment. Sourced from the City of Detroit Route Segments layer (ADR-001 §4.8). */
        SegmentProperties: {
            /** @description Stable identifier for the segment. OPEN QUESTION — not yet decided: this is either the stringified core.route_segment.id (a bigint identity column) or the source layer's OBJECTID. Those have different stability guarantees. Resolve before Stage D1 implements the query. */
            segment_id: string;
            /** @description Segment status (FR-05) — ADR-001 §4.8 */
            phase: string;
            /** @description Segment type (FR-06) — ADR-001 §4.8 */
            type: string;
        };
        /** @description One route segment as a GeoJSON Feature. */
        SegmentFeature: {
            /** @enum {string} */
            type: "Feature";
            geometry: components["schemas"]["LineStringGeometry"];
            properties: components["schemas"]["SegmentProperties"];
        };
        /** @description The full response body of GET /api/v1/segments — every route segment of the Joe Louis Greenway as a GeoJSON FeatureCollection. */
        SegmentFeatureCollection: {
            /** @enum {string} */
            type: "FeatureCollection";
            features: components["schemas"]["SegmentFeature"][];
        };
        /** @description Error payload in the Problem Details format — RFC 9457 (which obsoletes RFC 7807). One shape for every error this API returns, so a client can write one error handler and not one per endpoint. */
        Problem: {
            /**
             * Format: uri-reference
             * @description URI reference identifying the problem type. Stable — clients may branch on it. "about:blank" means "no type beyond the status code".
             * @default about:blank
             * @example /problems/rate-limited
             */
            type: string;
            /**
             * @description Short human-readable summary of the problem type. Does not change from occurrence to occurrence of the same type.
             * @example Too Many Requests
             */
            title: string;
            /**
             * Format: int32
             * @description HTTP status code, duplicated in the body. Present so the payload is self-describing when logged or forwarded away from its response.
             * @example 429
             */
            status: number;
            /**
             * @description Human-readable explanation specific to this occurrence. Safe for display to an end user. Must never contain a stack trace, SQL, a database identifier, or an internal hostname — NFR-SEC-03.
             * @example Request quota exceeded. Retry after 60 seconds.
             */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference identifying this specific occurrence. Correlates a user-reported error with a server log line.
             * @example /problems/rate-limited/01J8Z9K2QF
             */
            instance?: string;
        };
    };
    responses: {
        /** @description Too many requests from this client. See the open question in docs/walking_skeleton_plan.md — this shape holds only for rate limiting applied by this API. Rate limiting applied at the Cloudflare edge (ADR-001 4.7) never reaches Express and returns Cloudflare's own response body, not this one. */
        RateLimited: {
            headers: {
                /**
                 * @description Seconds to wait before retrying — RFC 9110 section 10.2.3.
                 * @example 60
                 */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unhandled server-side fault. The response body carries no diagnostic detail; the correlating detail is in the server log, found via "instance". */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A dependency this endpoint needs is unreachable — in practice, the PostGIS database. Distinct from 500 on purpose: 503 means "the API is up and its dependency is not", which is the exact condition the Stage F1 degradation test induces (NFR-AVL-02). The base map keeps loading; this endpoint alone fails. */
        ServiceUnavailable: {
            headers: {
                /** @description Seconds to wait before retrying, when a recovery estimate exists. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSegments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GeoJSON FeatureCollection of route segment LineStrings. Coordinates are WGS 84 (EPSG:4326), longitude then latitude — RFC 7946 §4. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": components["schemas"]["SegmentFeatureCollection"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
