/**
 * Stage C4 contract test — the committed fixture against the committed spec.
 *
 * WHAT THIS REPLACES, AND WHY
 *
 *   The previous version of this file imported `validateDocument` from
 *   `scripts/seed.mjs` and read `seed/segments.seed.geojson`. Both were deleted:
 *   seed/README.md records that the separate database seed file was removed
 *   because the ETL importer IS Stage C3's seed step, and because the deleted
 *   file was keyed on OBJECTID where field_mapping.csv row MAP-013 specifies
 *   OBJECT_ID. So this test could not import and could not run. It was not
 *   failing loudly — it was failing before reaching an assertion, which is
 *   worse, because a suite that errors on import can be mistaken for a suite
 *   that has nothing to say.
 *
 * THE SUBJECT
 *
 *   seed/segments.response.fixture.geojson — the expected GET /api/v1/segments
 *   response for the committed export, generated by
 *   scripts/seed/build-segments-fixture.mjs (`npm run fixture:build`).
 *   It exists, it is reproducible, and it is the artefact Stage D's endpoint
 *   will be compared against. That makes it a live subject rather than a lost
 *   one.
 *
 * NO SECOND VALIDATOR
 *
 *   Validation is delegated to scripts/contract/response-validator.mjs, which
 *   compiles components.schemas straight out of the spec at call time. Writing
 *   a second ajv setup here would create exactly the drift that file's header
 *   was written to prevent.
 *
 * WHAT THIS DELIBERATELY DOES NOT ASSERT
 *
 *   A response-size budget. Plan task D2 owns that, and its figure depends on
 *   NFR-PRF-01, which is unratified (plan section 9 item 3). This test MEASURES
 *   and PRINTS the minified size so D2 has a number that came from the artefact
 *   rather than from a document, but it does not gate on one. Asserting an
 *   unratified budget here would put a Stage D obligation inside a Stage C test.
 *
 *   Identity. seed/README.md is explicit that segment_id in this fixture is the
 *   source_ref (OBJECT_ID), not core.route_segment.id, which is
 *   GENERATED ALWAYS AS IDENTITY and unknowable outside the database. Asserting
 *   that segment_id equals a database identity would be asserting something the
 *   README states is false.
 */

import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
import { assertSegmentsResponse } from './contract/response-validator.mjs'

// M016 records this dataset as 51 segments, and
// scripts/seed/build-segments-fixture.mjs refuses to emit any other count.
// Asserted here rather than assumed, so a silently truncated fixture fails.
const EXPECTED_FEATURES = 51

const FIXTURE = new URL('../seed/segments.response.fixture.geojson', import.meta.url)

test('the committed fixture conforms to SegmentFeatureCollection in the spec', async (t) => {
  const raw = await readFile(FIXTURE, 'utf8')
  const document = JSON.parse(raw)

  // Schema conformance plus the Detroit bounding-box check, which is the
  // cheapest available proxy for "these coordinates are degrees, not metres".
  // RFC 7946 section 4 mandates WGS 84, and ST_AsGeoJSON on a projected
  // geometry emits structurally valid GeoJSON that draws in the Gulf of Guinea.
  const summary = assertSegmentsResponse(document)

  assert.equal(summary.features, EXPECTED_FEATURES)

  // Reported, not gated. Supersedes both figures stated in seed/README.md,
  // which contradict each other (26,043 in one paragraph, 26,030 in another).
  // Whichever is right, this is the measurement taken from the file itself.
  t.diagnostic(`minified response size: ${JSON.stringify(document).length} bytes`)
  t.diagnostic(`committed file size:    ${raw.length} bytes`)
})

test('every feature is a two-dimensional LineString with the contract properties', async () => {
  const document = JSON.parse(await readFile(FIXTURE, 'utf8'))

  for (const [index, feature] of document.features.entries()) {
    assert.equal(feature.type, 'Feature', `feature ${index} is not a Feature`)
    assert.equal(
      feature.geometry?.type,
      'LineString',
      `feature ${index} is ${feature.geometry?.type}, and core.route_segment is typed LineString`,
    )
    assert.ok(
      Array.isArray(feature.geometry.coordinates) && feature.geometry.coordinates.length >= 2,
      `feature ${index} has fewer than two positions`,
    )

    // A third ordinate would survive the schema and then fail the database,
    // where geom is geometry(LineString, 4326). ST_Force2D in the ETL is what
    // strips it; a fixture carrying one means the generator and the importer
    // disagree.
    for (const position of feature.geometry.coordinates) {
      assert.equal(
        position.length,
        2,
        `feature ${index} has a position with ${position.length} ordinates`,
      )
    }

    // segment_id, phase and type are required by the spec, so the schema check
    // above already covers their presence. Non-emptiness is the part a schema
    // with `type: string` does not catch.
    const p = feature.properties
    assert.ok(p.segment_id?.length, `feature ${index} has an empty segment_id`)
    assert.ok(p.phase?.length, `feature ${index} has an empty phase`)
    assert.ok(p.type?.length, `feature ${index} has an empty type`)
  }
})

test('source_ref values are unique, so the upsert key cannot collide', async () => {
  const document = JSON.parse(await readFile(FIXTURE, 'utf8'))

  // The (source, source_ref) upsert in scripts/etl/cityRouteSegments.js is only
  // safe if source_ref is unique. seed/README.md records that twenty values
  // exist in both the OBJECTID and OBJECT_ID key spaces and all twenty refer to
  // DIFFERENT segments — so a duplicate here is the signature of the two fields
  // having been confused again, which overwrites rows with no error and no
  // change in row count.
  const seen = new Map()
  for (const [index, feature] of document.features.entries()) {
    const ref = feature.properties.segment_id
    assert.ok(!seen.has(ref), `segment_id ${ref} appears at index ${seen.get(ref)} and ${index}`)
    seen.set(ref, index)
  }
  assert.equal(seen.size, EXPECTED_FEATURES)
})
